# Dependencies
highlighter:      rouge
markdown:         kramdown
kramdown:
  input: GFM

# Permalinks
permalink:        pretty

# Setup
title:            Thiago Marzagão
tagline:          ''
description:      ''
url:              https://thiagomarzagao.com
baseurl:          ""

author:
  name:           'Thiago Marzagão'
  url:            https://thiagomarzagao.com

paginate:         5
comments:         true
