# Dependencies
highlighter:      rouge
markdown:         kramdown
kramdown:
  input: GFM

# Permalinks
permalink:        pretty

# Setup
title:            Thiago Marzagão
tagline:          ''
description:      ''
url:              https://thiagomarzagao.com
baseurl:          ""

author:
  name:           'Thiago Marzagão'
  url:            https://thiagomarzagao.com

comments:         true

plugins:
  - jekyll-paginate



paginate: 5
paginate_path: "/blog/page:num/"
